### ISSUE TITLE
Tall mobs become visible after re-logging, blocking player's view.

### ISSUE THREAD

**Issue by iLemon** [FancyMcPlugins/FancyMorphs#2]
Short mobs like wolf, allay, dolphin etc all work fine.

Mobs that are taller than 1 block are all invisible (no name tag and no mob).

The 'Successfully morphed' message still sends and no errors in console.

Folia 1.20.1

**Comment by OliverSchlueter** [comment]
They _should_ only be invisible for you, because otherwise the entity would block your view

**Comment by iLemon** [comment]
That makes sense - thanks for clarifying! In that case, the bug here is that when you relog, the invisible mob appears and blocks your view:
![CleanShot 2023-12-07 at 15 13 14@2x](https://github.com/FancyMcPlugins/FancyMorphs/assets/18317307/e06fc91d-3b90-4d00-a6b5-6f91624d27bf)

**Comment by OliverSchlueter** [comment]
Should be fixed now
