### ISSUE TITLE
Suggestion: Add permissions for each individual morph

### ISSUE THREAD

**Issue by iLemon** [FancyMcPlugins/FancyMorphs#3]
Something like `fancymorphs.morph.chicken` would be great!

**Comment by OliverSchlueter** [comment]
I already added this in 5a43c8ce5e227bb05005fbc35588f9f432ebc428

Is it not working?

**Comment by iLemon** [comment]
> I already added this in [5a43c8c](https://github.com/FancyMcPlugins/FancyMorphs/commit/5a43c8ce5e227bb05005fbc35588f9f432ebc428)
> 
> Is it not working?

You're right, my bad - didn't see that commit. Works perfectly, thanks!
